# Generated by Django 5.0.4 on 2024-05-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quetsion_text',
            new_name='question_text',
        ),
    ]
